# Source: OJK KEP-21/D.04/2026, 21 Mei 2026 — DES Periode I 2026
# 618 listed/public-company entries before the document's 'Tidak Listing' section.
GROUPS={
'Emiten Syariah / Perusahaan Publik Syariah':'BANK,BBMI,BRIS,BTPS,JMAS,PNBS,SPOT',
'Energi':'AADI,ABMM,ADMR,ADRO,AKRA,ARII,ATLA,BBRM,BESS,BOAT,BSML,BSSR,BULL,BUMI,BYAN,CANI,CGAS,COAL,DEWA,DSSA,DWGL,ELSA,ENRG,FIRE,GEMS,HRUM,IATA,INDY,ITMA,ITMG,KKGI,KOPI,MAHA,MBAP,MCOL,MEDC,MKAP,MYOH,PGAS,PKPK,PSAT,PSSI,PTBA,PTIS,RAJA,RATU,RGAS,RMKE,RMKO,RUIS,SEMA,SGER,SICO,SMMT,SOCI,SUNI,TCPI,TEBE,TOBA,TPMA,UNIQ,WINS,WOWS',
'Barang Baku':'ADMG,AGII,AKPI,ALDO,ALKA,ANTM,APLI,ARCI,ASPR,AVIA,AYLS,BATR,BLES,BMSR,BRMS,BRNA,CHEM,CITA,CLPI,CTBN,DGWG,DKFT,EKAD,EPAC,ESIP,ESSA,FASW,FPNI,FWCT,GDST,GGRP,IFII,IFSH,IGAR,INCI,INKP,INTD,INTP,IPOL,ISSP,KDSI,KKES,LMSH,LTLS,MBMA,MDKA,MDKI,MINE,NICE,NICL,NIKL,OBMD,OKAS,PACK,PBID,PDPP,PICO,PPRI,PSAB,PTMR,SAMF,SBMA,SMBR,SMCB,SMGA,SMGR,SMKL,SMLE,SOLA,SPMA,SULI,TALF,TBMS,TINS,TIRT,TKIM,TPIA,TRST,UNIC,WTON,YPAS',
'Perindustrian':'AMFG,AMIN,APII,ARNA,ASGR,BINO,BLUE,CAKK,CCSI,CRSN,DYAN,FOLK,GPSO,HEXA,HOPE,HYGN,ICON,IKAI,IKBI,IMPC,JECC,JTPE,KBLI,KBLM,KIAS,KING,KOBX,KOIN,KONI,KUAS,LION,MARK,MFMI,MHKI,MLIA,MUTU,NAIK,NTBK,PADA,PTMP,SCCO,SKRN,SMIL,SOSS,SPTO,TIRA,TOTO,UNTR,VISI,VOKS,WIDI',
'Barang Konsumen Primer':'AALI,ADES,AGAR,AISA,AMMS,ASHA,AYAM,BISI,BOBA,BRRC,BUAH,BUDI,BWPT,CAMP,CEKA,CLEO,CMRY,CPIN,CPRO,CSRA,DAYA,DEWI,DMND,DSFI,DSNG,EPMT,EURO,FISH,FLMC,FOOD,FORE,GOOD,GRPM,GULA,GUNA,GZCO,HERO,HOKI,ICBP,IKAN,INDF,JARR,JAWA,JPFA,KEJU,KINO,KMDS,LSIP,MAIN,MAXI,MBTO,MKTR,MLPL,MPPA,MRAT,MSJA,MYOR,NANO,NASI,NAYZ,NEST,NSSS,PCAR,PGUN,PNGO,PSDN,PSGO,PTPS,RANC,ROTI,SDPC,SGRO,SIMP,SIPD,SKBM,SKLT,SMAR,STAA,STTP,TAPG,TCID,TGKA,TGUK,TLDN,UCID,UDNG,ULTJ,UNVR,VICI,WAPO,YUPI',
'Barang Konsumen Non-Primer':'ACES,AEGS,ASLC,AUTO,BABY,BAIK,BAUT,BAYU,BELL,BIKE,BLTZ,BMBL,BMTR,BOGA,BOLT,BRAM,CINT,CNMA,CSAP,CSMI,DEPO,DOOH,DOSS,DRMA,EAST,ECII,ENAK,ERAA,ERAL,ERTX,ESTA,FAST,FILM,GDYR,GEMA,GJTL,GOLF,GRPH,GWSA,HAJJ,HRTA,IDEA,IIKP,INDR,INDS,IPTV,ISAP,JGLE,JIHD,KAQI,KICI,KLIN,KOTA,KPIG,LFLO,LIVE,LMAX,LMPI,LPIN,LPPF,MAPA,MAPB,MAPI,MDIA,MDIY,MEJA,MERI,MGLV,MICE,MKNT,MNCN,MPMX,MSIN,MSKY,OLIV,PANR,PART,PDES,PGLI,PJAA,PLAN,PMJS,PMUI,POLU,PSKT,PTSP,PZZA,RAAM,RALS,SCNP,SHID,SLIS,SMSM,SNLK,SOFA,SOTS,SPRE,SSTM,SWID,TFCO,TMPO,TOOL,TRIS,TYRE,UFOE,VERN,VKTR,WOOD,YELO,ZONE',
'Kesehatan':'BMHS,CARE,CHEK,DGNS,DVLA,HALO,HEAL,IKPM,IRRA,KLBF,LABS,MDLA,MEDS,MERK,MIKA,MMIX,MTMH,OBAT,OMED,PEHA,PEVE,PRAY,PRDA,PRIM,RSCH,RSGK,SAME,SCPI,SIDO,SILO,SOHO,SURI,TSPC',
'Keuangan':'SRTG,PALM,DEFI',
'Properti & Real Estat':'ADCP,AMAN,APLN,ASPI,ASRI,ATAP,BAPI,BBSS,BCIP,BEST,BIPP,BKDP,BKSL,BSBK,BSDE,CITY,CSIS,CTRA,DADA,DILD,DMAS,DUTI,ELTY,EMDE,FMII,GMTD,GPRA,GRIA,HBAT,HOMI,INPP,IPAC,JRPT,KBAG,KIJA,KOCI,LAND,LPCK,LPLI,MKPI,MMLP,MSIE,MTLA,MTSM,NZIA,PAMG,PLIN,POLI,PURI,RBMS,REAL,RELF,RISE,ROCK,RODA,SAGE,SATU,SMDM,SMRA,UANG,URBN,VAST,WINR',
'Teknologi':'AREA,ATIC,AWAN,AXIO,BELI,CASH,CHIP,CYBR,DCII,DIVA,DMMX,ELIT,GLVA,HDIT,IOTF,IRSX,JATI,KIOS,KREN,LUCK,MCAS,MLPT,MPIX,MSTI,MTDL,NFCX,PGJO,PTSN,RUNS,TFAS,TOSK,TRON,UVCR,WGSH,WIFI,WIRG,ZYRX',
'Infrastruktur':'ASLI,BALI,BDKR,CASS,CMNP,DATA,DGIK,EXCL,FIMP,GHON,GOLD,HADE,IBST,IDPR,INET,IPCM,ISAT,JAST,JKON,JSMR,KARW,KEEN,KETR,KOKA,MANG,META,MORA,MPOW,MTEL,MTPS,NRCA,PORT,POWR,PPRE,PTPP,PTPW,SMKM,SSIA,SUPR,TAMA,TLKM,TOTL,WEGE',
'Transportasi & Logistik':'AKSI,ASSA,BIRD,BLOG,BLTA,CMPP,ELPI,GIAA,GTRA,HAIS,HATM,HELI,JAYA,KJEN,KLAS,LAJU,LOPI,LRNA,MIRA,MITI,NELY,PJHB,PPGL,PURA,RCCC,SAFE,SAPX,SMDR,TAXI,TMAS,TNCA,TRJA,TRUK,WBSA,WEHA',
'Perusahaan Publik':'GRHA'}
SECTOR_BY_TICKER={t:s for s,csv in GROUPS.items() for t in csv.split(',')}
TICKERS=list(SECTOR_BY_TICKER)
DES_SOURCE='OJK KEP-21/D.04/2026 — DES Periode I 2026 (21 Mei 2026)'
