services:
  - type: web
    name: wiss-fair-value-lab
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    autoDeploy: true
